name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]
    # Optional: Only run on specific file changes
    # paths:
    #   - "src/**/*.ts"
    #   - "src/**/*.tsx"
    #   - "src/**/*.js"
    #   - "src/**/*.jsx"

permissions:
  contents: read
  pull-requests: read
  issues: read
  id-token: write

jobs:
  claude-review:
    uses: viio-io/github-workflows/.github/workflows/claude-code-review.yml@main
    secrets:
      claude-code-oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
