---
name: Continuous Integration Check

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:

  ci:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Desktop.Agent on MacOS
        run: OVEO_CUSTOMER_KEY="EXAMPLE_KEY" ./macos.install.sh
