name: Continuous Integration Check

on:
  pull_request:
    branches: main
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  macos-install:
    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v3

      - name: Install Desktop.Agent on MacOS
        run: VIIO_CUSTOMER_KEY="EXAMPLE_KEY" VIIO_EMPLOYEE_EMAIL="user@test.com" ./macos.install.sh

      - name: Check configuration file content
        run: |
          CONTENT='{"CustomerKey":"EXAMPLE_KEY","EmployeeEmail":"user@test.com"}'
          if [[ $(sudo cat /etc/viio.conf) != "$CONTENT" ]]; then
            exit 1
          fi

  windows-install:
    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v3

      - name: Install Desktop.Agent on Windows
        run: ./windows.install.ps1 -EmployeeEmail "" -CustomerKey "EXAMPLE_KEY"

  ci:
    needs: [macos-install, windows-install]
    name: Continuous Integration Check
    runs-on: ubuntu-latest
    if: always()

    steps:

      - name: Report failure
        if: needs.macos-install.result == 'failure' || needs.windows-install.result == 'failure'
        run: exit 1

      - name: Report success
        run: exit 0
