---
name: Continuous Integration Check

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review ]

jobs:

  macos-install:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Desktop.Agent on MacOS
        run: OVEO_CUSTOMER_KEY="EXAMPLE_KEY" ./macos.install.sh
        
      - name: Check configuration file content
        run: |
          content = '{"CustomerKey":"EXAMPLE_KEY","EmployeeEmail":""}'
          if [[ $(< /etc/oveo.conf != "$content" ]]; then
            exit 1
          fi
